/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef velassco_CONSTANTS_H
#define velassco_CONSTANTS_H

#include "velassco_types.h"



class velasscoConstants {
 public:
  velasscoConstants();

};

extern const velasscoConstants g_velassco_constants;



#endif
