/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef com_CONSTANTS_H
#define com_CONSTANTS_H

#include "com_types.h"



class comConstants {
 public:
  comConstants();

};

extern const comConstants g_com_constants;



#endif
