/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef VELaSSCo_CONSTANTS_H
#define VELaSSCo_CONSTANTS_H

#include "VELaSSCo_types.h"



class VELaSSCoConstants {
 public:
  VELaSSCoConstants();

};

extern const VELaSSCoConstants g_VELaSSCo_constants;



#endif
